// Minimal QR encoder: byte mode, error level L, versions 1-40.
//
// It exists because the page it serves must make zero network requests, and the
// page it replaces fetched every QR from api.qrserver.com -- which handed a
// third party the entire recipe, in plain text, in a URL.
//
// Error level L only. A share link is long (README.md records 652 base64url
// characters for an 11-ingredient recipe), and L keeps the symbol version, and
// therefore the module size on a phone screen, as large as possible. The codes
// are read off a clean screen, not off a stained printout, so the extra
// redundancy of M/Q/H buys nothing here.
//
// Mask selection follows ISO/IEC 18004 penalty rules N1..N4, so the output is
// byte-identical to independent encoders; tests/qr_test.mjs pins that against
// matrices generated by Nayuki's qrcodegen.

const ECC_L_BITS = 1; // Error level L, as spelled in the format-information field.

// One row per version: [error-correction codewords per block, group 1 block
// count, group 1 data codewords per block, group 2 block count, group 2 data
// codewords]. Group 2 is 0, 0 for the versions that have a single group, and
// group 1 always holds the shorter blocks -- the order the interleaver needs.
const ECC_L = [
  [7, 1, 19, 0, 0],
  [10, 1, 34, 0, 0],
  [15, 1, 55, 0, 0],
  [20, 1, 80, 0, 0],
  [26, 1, 108, 0, 0],
  [18, 2, 68, 0, 0],
  [20, 2, 78, 0, 0],
  [24, 2, 97, 0, 0],
  [30, 2, 116, 0, 0],
  [18, 2, 68, 2, 69],
  [20, 4, 81, 0, 0],
  [24, 2, 92, 2, 93],
  [26, 4, 107, 0, 0],
  [30, 3, 115, 1, 116],
  [22, 5, 87, 1, 88],
  [24, 5, 98, 1, 99],
  [28, 1, 107, 5, 108],
  [30, 5, 120, 1, 121],
  [28, 3, 113, 4, 114],
  [28, 3, 107, 5, 108],
  [28, 4, 116, 4, 117],
  [28, 2, 111, 7, 112],
  [30, 4, 121, 5, 122],
  [30, 6, 117, 4, 118],
  [26, 8, 106, 4, 107],
  [28, 10, 114, 2, 115],
  [30, 8, 122, 4, 123],
  [30, 3, 117, 10, 118],
  [30, 7, 116, 7, 117],
  [30, 5, 115, 10, 116],
  [30, 13, 115, 3, 116],
  [30, 17, 115, 0, 0],
  [30, 17, 115, 1, 116],
  [30, 13, 115, 6, 116],
  [30, 12, 121, 7, 122],
  [30, 6, 121, 14, 122],
  [30, 17, 122, 4, 123],
  [30, 4, 122, 18, 123],
  [30, 20, 117, 4, 118],
  [30, 19, 118, 6, 119],
];

/** Unpack one version's block layout from the flat table. */
function eccLayout(version) {
  const [ecLen, count1, data1, count2, data2] = ECC_L[version - 1];
  const groups = [[count1, data1]];
  if (count2 > 0) groups.push([count2, data2]);
  return { ecLen, groups };
}

// Alignment-pattern centre coordinates, indexed from version 2.
const ALIGNMENT_POS = [
  [6, 18],
  [6, 22],
  [6, 26],
  [6, 30],
  [6, 34],
  [6, 22, 38],
  [6, 24, 42],
  [6, 26, 46],
  [6, 28, 50],
  [6, 30, 54],
  [6, 32, 58],
  [6, 34, 62],
  [6, 26, 46, 66],
  [6, 26, 48, 70],
  [6, 26, 50, 74],
  [6, 30, 54, 78],
  [6, 30, 56, 82],
  [6, 30, 58, 86],
  [6, 34, 62, 90],
  [6, 28, 50, 72, 94],
  [6, 26, 50, 74, 98],
  [6, 30, 54, 78, 102],
  [6, 28, 54, 80, 106],
  [6, 32, 58, 84, 110],
  [6, 30, 58, 86, 114],
  [6, 34, 62, 90, 118],
  [6, 26, 50, 74, 98, 122],
  [6, 30, 54, 78, 102, 126],
  [6, 26, 52, 78, 104, 130],
  [6, 30, 56, 82, 108, 134],
  [6, 34, 60, 86, 112, 138],
  [6, 30, 58, 86, 114, 142],
  [6, 34, 62, 90, 118, 146],
  [6, 30, 54, 78, 102, 126, 150],
  [6, 24, 50, 76, 102, 128, 154],
  [6, 28, 54, 80, 106, 132, 158],
  [6, 32, 58, 84, 110, 136, 162],
  [6, 26, 54, 82, 110, 138, 166],
  [6, 30, 58, 86, 114, 142, 170],
];

const PENALTY = { adjacent: 3, block: 3, finderLike: 40, balance: 10 };

// GF(256) with the QR primitive polynomial x^8 + x^4 + x^3 + x^2 + 1.
const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);
for (let i = 0, x = 1; i < 255; i++) {
  GF_EXP[i] = x;
  GF_LOG[x] = i;
  x = (x << 1) ^ (x & 0x80 ? 0x11d : 0);
}
for (let i = 255; i < 512; i++) GF_EXP[i] = GF_EXP[i - 255];

function gfMul(a, b) {
  if (a === 0 || b === 0) return 0;
  return GF_EXP[GF_LOG[a] + GF_LOG[b]];
}

/** Reed-Solomon generator polynomial of the given degree, highest term first. */
function generatorPoly(degree) {
  let poly = [1];
  for (let i = 0; i < degree; i++) {
    const next = new Array(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j];
      next[j + 1] ^= gfMul(poly[j], GF_EXP[i]);
    }
    poly = next;
  }
  return poly;
}

/** The `ecLen` error-correction codewords for one data block. */
function reedSolomon(data, ecLen) {
  const gen = generatorPoly(ecLen);
  const work = new Uint8Array(data.length + ecLen);
  work.set(data);

  for (let i = 0; i < data.length; i++) {
    const factor = work[i];
    if (factor === 0) continue;
    for (let j = 0; j < gen.length; j++) work[i + j] ^= gfMul(gen[j], factor);
  }
  return work.subarray(data.length);
}

/** Total data codewords for a version at error level L. */
function dataCodewordCount(version) {
  return eccLayout(version).groups.reduce(
    (sum, [count, dataLen]) => sum + count * dataLen,
    0,
  );
}

/** Byte mode spends 8 bits on the length below version 10 and 16 bits above. */
function charCountBits(version) {
  return version < 10 ? 8 : 16;
}

/** The smallest version that fits `byteLength` bytes of byte-mode data. */
function chooseVersion(byteLength) {
  for (let version = 1; version <= 40; version++) {
    const needed = 4 + charCountBits(version) + 8 * byteLength;
    if (needed <= dataCodewordCount(version) * 8) return version;
  }
  throw new Error(
    `${byteLength} bytes will not fit in a QR symbol at error level L`,
  );
}

/** Data bits -> the full interleaved codeword stream for the symbol. */
function buildCodewords(version, bytes) {
  const { ecLen, groups } = eccLayout(version);
  const capacityBits = dataCodewordCount(version) * 8;
  const bits = [];

  const push = (value, width) => {
    for (let i = width - 1; i >= 0; i--) bits.push((value >>> i) & 1);
  };

  push(0b0100, 4); // Byte mode.
  push(bytes.length, charCountBits(version));
  for (const byte of bytes) push(byte, 8);

  // In byte mode the stream always lands four bits short of a codeword boundary,
  // so the four-bit terminator and the pad-to-boundary zeros are the same four
  // bits. The capacity guard is what truncates the terminator in a full symbol.
  while (bits.length < capacityBits && bits.length % 8 !== 0) bits.push(0);
  const codewords = new Uint8Array(capacityBits / 8);
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | (bits[i + j] ?? 0);
    codewords[i / 8] = byte;
  }
  for (
    let i = Math.ceil(bits.length / 8), alt = 0;
    i < codewords.length;
    i++, alt++
  ) {
    codewords[i] = alt % 2 === 0 ? 0xec : 0x11;
  }

  // Split into blocks, then interleave data and error correction separately.
  const dataBlocks = [];
  let offset = 0;
  for (const [count, dataLen] of groups) {
    for (let i = 0; i < count; i++) {
      dataBlocks.push(codewords.subarray(offset, offset + dataLen));
      offset += dataLen;
    }
  }
  const ecBlocks = dataBlocks.map((block) => reedSolomon(block, ecLen));

  const result = [];
  const longest = Math.max(...dataBlocks.map((block) => block.length));
  for (let i = 0; i < longest; i++) {
    for (const block of dataBlocks) if (i < block.length) result.push(block[i]);
  }
  for (let i = 0; i < ecLen; i++) {
    for (const block of ecBlocks) result.push(block[i]);
  }
  return Uint8Array.from(result);
}

/** A mutable square symbol: module colours plus which cells are function patterns. */
function blankSymbol(version) {
  const size = version * 4 + 17;
  return {
    size,
    modules: new Uint8Array(size * size),
    reserved: new Uint8Array(size * size),
  };
}

function drawFunctionPatterns(symbol, version) {
  const { size, modules, reserved } = symbol;
  const set = (row, col, dark) => {
    modules[row * size + col] = dark ? 1 : 0;
    reserved[row * size + col] = 1;
  };

  // Reserve the three corners wholesale: finder, separator and format info all
  // live inside these blocks, which keeps the data placement check to one array.
  const reserveBlock = (row0, col0, rows, cols) => {
    for (let r = row0; r < row0 + rows; r++) {
      for (let c = col0; c < col0 + cols; c++) reserved[r * size + c] = 1;
    }
  };
  reserveBlock(0, 0, 9, 9);
  reserveBlock(0, size - 8, 9, 8);
  reserveBlock(size - 8, 0, 8, 9);

  for (const [row0, col0] of [
    [0, 0],
    [0, size - 7],
    [size - 7, 0],
  ]) {
    for (let dr = 0; dr < 7; dr++) {
      for (let dc = 0; dc < 7; dc++) {
        const edge = dr === 0 || dr === 6 || dc === 0 || dc === 6;
        const core = dr >= 2 && dr <= 4 && dc >= 2 && dc <= 4;
        set(row0 + dr, col0 + dc, edge || core);
      }
    }
  }

  for (let i = 8; i < size - 8; i++) {
    set(6, i, i % 2 === 0);
    set(i, 6, i % 2 === 0);
  }

  const centres = version >= 2 ? ALIGNMENT_POS[version - 2] : [];
  for (const row of centres) {
    for (const col of centres) {
      // The three positions that coincide with a finder pattern are skipped.
      if (
        (row === 6 && col === 6) ||
        (row === 6 && col === size - 7) ||
        (row === size - 7 && col === 6)
      ) {
        continue;
      }
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          set(
            row + dr,
            col + dc,
            Math.abs(dr) === 2 || Math.abs(dc) === 2 || (dr === 0 && dc === 0),
          );
        }
      }
    }
  }

  set(size - 8, 8, true); // The always-dark module.

  if (version >= 7) {
    let rem = version;
    for (let i = 0; i < 12; i++) rem = (rem << 1) ^ ((rem >>> 11) * 0x1f25);
    const bits = (version << 12) | rem;

    for (let i = 0; i < 18; i++) {
      const dark = ((bits >>> i) & 1) === 1;
      const far = size - 11 + (i % 3);
      const near = Math.floor(i / 3);
      set(near, far, dark);
      set(far, near, dark);
    }
  }
}

/** Place the codeword bits in the standard two-column upward/downward zigzag. */
function drawCodewords(symbol, codewords) {
  const { size, modules, reserved } = symbol;
  let bit = 0;
  const totalBits = codewords.length * 8;

  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5; // Column 6 is the timing pattern; it is never paired.

    for (let vert = 0; vert < size; vert++) {
      for (let j = 0; j < 2; j++) {
        const col = right - j;
        const upward = ((right + 1) & 2) === 0;
        const row = upward ? size - 1 - vert : vert;
        if (reserved[row * size + col]) continue;

        // Bits past the data stream are the remainder bits, which stay light.
        if (bit < totalBits) {
          modules[row * size + col] =
            (codewords[bit >>> 3] >>> (7 - (bit & 7))) & 1;
        }
        bit++;
      }
    }
  }
}

const MASK_RULES = [
  (row, col) => (row + col) % 2 === 0,
  (row, _col) => row % 2 === 0,
  (_row, col) => col % 3 === 0,
  (row, col) => (row + col) % 3 === 0,
  (row, col) => (Math.floor(row / 2) + Math.floor(col / 3)) % 2 === 0,
  (row, col) => ((row * col) % 2) + ((row * col) % 3) === 0,
  (row, col) => (((row * col) % 2) + ((row * col) % 3)) % 2 === 0,
  (row, col) => (((row + col) % 2) + ((row * col) % 3)) % 2 === 0,
];

/** XOR the mask over every data module. Applying it twice restores the symbol. */
function applyMask(symbol, mask) {
  const { size, modules, reserved } = symbol;
  const rule = MASK_RULES[mask];

  for (let row = 0; row < size; row++) {
    for (let col = 0; col < size; col++) {
      if (!reserved[row * size + col] && rule(row, col))
        modules[row * size + col] ^= 1;
    }
  }
}

function drawFormatInfo(symbol, mask) {
  const { size, modules } = symbol;

  // BCH(15,5) over the 5-bit level+mask field, then the fixed 0x5412 mask.
  const data = (ECC_L_BITS << 3) | mask;
  let rem = data;
  for (let i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >>> 9) * 0x537);
  const bits = (((data << 10) | rem) ^ 0x5412) & 0x7fff;

  const set = (row, col, i) => {
    modules[row * size + col] = (bits >>> i) & 1;
  };

  for (let i = 0; i <= 5; i++) set(i, 8, i);
  set(7, 8, 6);
  set(8, 8, 7);
  set(8, 7, 8);
  for (let i = 9; i < 15; i++) set(8, 14 - i, i);

  for (let i = 0; i < 8; i++) set(8, size - 1 - i, i);
  for (let i = 8; i < 15; i++) set(size - 15 + i, 8, i);
}

/**
 * ISO/IEC 18004 penalty score, transcribed from the run-history formulation.
 *
 * The finder-like rule (N3) is the one every naive implementation gets subtly
 * wrong, so it uses the sliding seven-run history rather than a substring match.
 */
export function penaltyScore(symbol) {
  const { size, modules } = symbol;
  let score = 0;

  const addHistory = (runLength, history) => {
    // A run that starts at the edge is treated as if a light border preceded it.
    if (history[0] === 0) runLength += size;
    history.pop();
    history.unshift(runLength);
  };

  const countPatterns = (h) => {
    const n = h[1];
    const core =
      n > 0 && h[2] === n && h[3] === n * 3 && h[4] === n && h[5] === n;
    return (
      (core && h[0] >= n * 4 && h[6] >= n ? 1 : 0) +
      (core && h[6] >= n * 4 && h[0] >= n ? 1 : 0)
    );
  };

  // Rows then columns, sharing one scan so N1 and N3 stay in step.
  for (const byRow of [true, false]) {
    for (let major = 0; major < size; major++) {
      let runColor = 0;
      let runLength = 0;
      const history = [0, 0, 0, 0, 0, 0, 0];

      for (let minor = 0; minor < size; minor++) {
        const value = byRow
          ? modules[major * size + minor]
          : modules[minor * size + major];
        if (value === runColor) {
          runLength++;
          if (runLength === 5) score += PENALTY.adjacent;
          else if (runLength > 5) score++;
        } else {
          addHistory(runLength, history);
          if (!runColor) score += countPatterns(history) * PENALTY.finderLike;
          runColor = value;
          runLength = 1;
        }
      }

      if (runColor) {
        addHistory(runLength, history);
        runLength = 0;
      }
      addHistory(runLength + size, history);
      score += countPatterns(history) * PENALTY.finderLike;
    }
  }

  for (let row = 0; row < size - 1; row++) {
    for (let col = 0; col < size - 1; col++) {
      const value = modules[row * size + col];
      const same =
        value === modules[row * size + col + 1] &&
        value === modules[(row + 1) * size + col] &&
        value === modules[(row + 1) * size + col + 1];
      if (same) score += PENALTY.block;
    }
  }

  const dark = modules.reduce((sum, value) => sum + value, 0);
  const total = size * size;
  score +=
    (Math.ceil(Math.abs(dark * 20 - total * 10) / total) - 1) * PENALTY.balance;
  return score;
}

/**
 * Encode text as a QR symbol.
 *
 * Returns `{version, mask, size, modules}` where `modules` is a row-major
 * Uint8Array of 0/1 without a quiet zone; the caller adds the border.
 */
export function encodeQr(text, { mask = null } = {}) {
  const bytes = new TextEncoder().encode(String(text));
  const version = chooseVersion(bytes.length);
  const codewords = buildCodewords(version, bytes);

  const build = (candidate) => {
    const symbol = blankSymbol(version);
    drawFunctionPatterns(symbol, version);
    drawCodewords(symbol, codewords);
    applyMask(symbol, candidate);
    drawFormatInfo(symbol, candidate);
    return symbol;
  };

  if (mask !== null) {
    const symbol = build(mask);
    return { version, mask, size: symbol.size, modules: symbol.modules };
  }

  // The standard picks the lowest-penalty mask; ties go to the lower index.
  let best = null;
  for (let candidate = 0; candidate < 8; candidate++) {
    const symbol = build(candidate);
    const score = penaltyScore(symbol);
    if (!best || score < best.score) best = { score, mask: candidate, symbol };
  }
  return {
    version,
    mask: best.mask,
    size: best.symbol.size,
    modules: best.symbol.modules,
  };
}

/**
 * An SVG path covering every dark module, in a coordinate system of one unit per
 * module offset by the quiet zone. One path beats thousands of <rect> elements.
 */
export function qrPath(symbol, quietZone = 4) {
  const parts = [];
  for (let row = 0; row < symbol.size; row++) {
    for (let col = 0; col < symbol.size; col++) {
      if (symbol.modules[row * symbol.size + col]) {
        parts.push(`M${col + quietZone} ${row + quietZone}h1v1h-1z`);
      }
    }
  }
  return parts.join("");
}
